### ISSUE TITLE
12V led strip

### ISSUE THREAD

**Issue by malinin24** [stanleyondrus/LedBoxV2#1]
How it work with 12V led strip like WS2815?
WS2815 need 12V logic level.

**Comment by stanleyondrus** [comment]
Even the 12V led strips like WS2815 still require 5V logic level, which the LedBox uses.
I can see where your confusion comes from. The datasheet is poorly written, and this AMR figure for WS2815 is misleading.
![screen1](https://user-images.githubusercontent.com/10361168/225253471-8d646562-6557-4519-89c2-d708787ba45b.PNG)
Right on the next page they respecify VDD to be 5V.
![screen2](https://user-images.githubusercontent.com/10361168/225253775-ec13d243-3994-4955-ac86-9cf53440daff.PNG)
If you check the same figure in the newer datasheet for WS2815B, it is fixed.
![screen3](https://user-images.githubusercontent.com/10361168/225257327-edec9d09-366d-495a-9eb2-2e9e359ca7ae.PNG)
And since WS2815B is the only version available on [Worldsemi's website](http://www.world-semi.com/solution/list-4-1.html), I believe that most strips advertised as WS2815 nowadays, are in fact WS2815B.

**Comment by malinin24** [comment]
I bought a 2815 LED strip on aliexpress. It does not work from 5 volts of logic. Judging by the wiring diagram of the LEDs, the VCC output is connected directly to 12 volts. When the 12 volt logic level is applied, the LEDs will light up. While I don’t have a normal 5 volt to 12 volt logic level converter, I can’t fully check the tape.

**Comment by stanleyondrus** [comment]
Can you share the link to the strip you are talking about? Also, it would be helpful if you provided a picture of your setup, and information on what controller you used to test the 5V and 12V logic.

**Comment by malinin24** [comment]
I am very sorry. The controller was faulty, everything worked from 5V logic.
